%YAML:1.0



# Accepted feature depth bounds
upper_depth: 10000.0
lower_depth: 300.0

# for feature detection
scale_facotr: 1.2
max_level: 5
max_feature_num: 400
feature_sigma: 0.5

# How many loops in optimizer iteration
local_iter: 11
global_iter: 12

# 1 for print debug info, 0 for not
local_print: 0
global_print: 0

# 1 for verbose, 0 for non-verbose
local_verbose: 0
global_verbose: 0

# 1 for BA with 3d MapPoint constraint, 
# 0 for BA with 2d MapPoint constraint on images.
## Please keep it 0 now
local_3d: 0

# Robust kernel for 2d MapPoint constraint
th_huber2: 5.991 


# For odometry uncertanty
odo_x_uncertain: 0.01
odo_y_uncertain: 0.01
odo_theta_uncertain: 0.01

# For odometry noise (in a moment) (unit: mm, rad)
odo_x_steady_noise: 1
odo_y_steady_noise: 1
odo_theta_steady_noise: 0.005

# Tracking frequency
fps: 30

# How many images, useless if subscribe to topics 
img_num: 3104


# For map storage
## 1 if use previously saved map, 0 if not
use_prev_map: 0
## 1 if save map when exit, 0 if not
save_new_map: 0
## 1 if disable SLAM and do localization only (use_prev_map must be 1), 0 if do SLAM
localization_only: 0
## map file config
read_map_file_name: "se2lam.map"
read_map_file_path: "/home/fzheng/dataset/r4-007-save-map/"
write_map_file_name: "se2lam.map"
write_map_file_path: "/home/fzheng/dataset/r4-007-save-map/"
